controller_list:
  - name: "motoman"
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints: 
      - joint_s
      - joint_l
      - joint_e
      - joint_u
      - joint_r
      - joint_b
      - joint_t