# sensors:
#   - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
#     image_topic: /camera/depth/image_rect_raw
#     queue_size: 1
#     near_clipping_plane_distance: 0.4
#     far_clipping_plane_distance: 0.8
#     shadow_threshold: 0.2
#     padding_scale: 4.0
#     padding_offset: 0.03
#     max_update_rate: 1.0
#     filtered_cloud_topic: filtered_cloud

sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /camera/depth/color/points
    max_range: 0.8
    point_subsample: 100
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 1.0
    filtered_cloud_topic: filtered_cloud

